# Generated by Django 5.2.4 on 2025-07-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_category_produto_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.category'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Indica se o produto está disponível para venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade do produto em estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de exibição do produto', null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome do produto', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda do produto', max_digits=10),
        ),
    ]
