# Generated by Django 5.2.4 on 2025-07-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_rename_category_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='category',
            new_name='categoria',
        ),
    ]
