# Generated by Django 5.2.4 on 2025-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_loja', '0003_alter_contactrequest_options_contactrequest_assunto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='Contato',
        ),
    ]
